version: '3.3'
services:
  mysql:
    container_name: int221-mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: 'localhost'
      MYSQL_USER: int221
      MYSQL_PASSWORD: xt,[A#h+Zf,vMJ;e)8mV
    volumes:
      - "./database/init.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./database/data.sql:/docker-entrypoint-initdb.d/2.sql"
    networks:
        - int221-network
  spring:
    container_name: int221-spring
    image: ghcr.io/int221-31-33-43/kaofood_back-end:latest
    restart: always
    ports:
      - "8443:8443"
    links:
      - mysql:database
    networks:
      int221-network:
        ipv4_address: 172.16.0.101
  nodejs:
    container_name: int221-node.js
    image: ghcr.io/int221-31-33-43/kaofood_front-end:latest
    restart: always
    links:
      - spring
    networks:
      - int221-network
  web:
    image: nginx:alpine
    container_name: int221-nginx
    ports:
      - "443:443"
      - "80:80"
    links:
      - nodejs
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/zerossl:/etc/ssl
    networks:
      - int221-network
        
networks:
    int221-network:
      ipam:
        driver: bridge
        config:
          - subnet: 172.16.0.0/24
