version: '3.3'
services:
  mysql-server:
    container_name: int221-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: 'localhost'
      MYSQL_USER: int221
      MYSQL_PASSWORD: xt,[A#h+Zf,vMJ;e)8mV
    ports:
      - '3306:3306'
    volumes:
      - "./database/init.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./database/data.sql:/docker-entrypoint-initdb.d/2.sql"
    networks:
        - int221-network
  backend:
    container_name: int221-spring
    image: ghcr.io/int221-31-33-43/kaofood_back-end:latest
    ports:
      - '8080:8080'
    restart: always
    links:
      - mysql-server:db
    networks:
        - int221-network
  frontend:
    container_name: int221-node.js
    image: ghcr.io/int221-31-33-43/kaofood_front-end:latest
    ports:
      - "80:80"
    restart: always
    links:
      - backend
    networks:
      - int221-network
        
networks:
    int221-network:
        driver: bridge
