USE `kaofood` ;
insert into Category(CateId,CateName) values (1,'food');
insert into Size(SizeId,SizeValue) values (1,'Jumbo');
insert into Size(SizeId,SizeValue) values (2,'For Adult');
insert into Size(SizeId,SizeValue) values (3,'For Kid');
insert into Menu(MenuId,MenuName,Descript,Cost,Price,ImagePath,CateId) values (1,'Steak','Nice Meat',200.50,250,'test',1);
insert into Menu(MenuId,MenuName,Descript,Cost,Price,ImagePath,CateId) values (2,'Curry','Just Curry',300.56,350,'test2',1);
insert into Menu(MenuId,MenuName,Descript,Cost,Price,ImagePath,CateId) values (3,'ต้มยำกุ้ง','เป็นซุปแบบไทยที่เป็นที่รู้จักมากที่สุดและเป็นที่นิยมมากที่สุดไม่เฉพาะแต่ในเมืองไทยเท่านั้น แต่ยังเป็นที่นิยมในร้านอาหาร (และครัวไทย) อื่นๆทั่วโลก ต้มยำเป็นซุปรสเปรี้ยวปรุงด้วยเครื่องเทศของไทยที่เป็นที่นิยมหลากหลายชนิด: ทั้งตะไคร้กลิ่นหอมหวน แง่งข่าสด และใบมะกรูด',80.39,150,'test4',1);
insert into Menu(MenuId,MenuName,Descript,Cost,Price,ImagePath,CateId) values (4,'ชาเย็น','ชาไทยกลิ่นหอม ใสนมข้นรสหวานมัน ราดด้วยนมสดตัดกับสีส้มอ่อน ทำให้ได้เครื่องดื่มรสชาตินุ่มละมุน จนติดอันดับ 27 จาก 50อันดับเครื่องดื่มที่อร่อยที่สุดในโลก',10,20,'test5',2);
insert into Menu(MenuId,MenuName,Descript,Cost,Price,ImagePath,CateId) values (5,'ทองหยอด','ทองหยอดเป็นขนมไทยโบราณที่เสิร์ฟในโอกาสพิธีมงคลพิเศษ ทำจากไข่แดงผสมกับแป้งแล้วต้มในน้ำเชื่อม เป็นหนึ่งในขนมหวานตระกูลทองอย่างทองหยิบ ทองหยอด ฝอยทอง มีความหมายว่าให้ผู้ที่รับประทานมีเงินทองโชคลาภไหลมาเทมา',40,60,'test6',3);
insert into Menu_has_Size(sizeid,menuid) values (1,1);
insert into Menu_has_Size(sizeid,menuid) values (2,1);
insert into Menu_has_Size(sizeid,menuid) values (3,1);
